name: publish-site

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
        base_url: ''
        path_to_notebooks: docs # the site lives in the docs/ subdirectory

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
    with:
        publish_dir: docs/_build/html # ...so the built site is under docs/
